test a workflow to be both dispatchable and callable

diff --git a/.github/workflows/build_starter.yml b/.github/workflows/build_starter.yml
--- a/.github/workflows/build_starter.yml
+++ b/.github/workflows/build_starter.yml
@@ -2,6 +2,9 @@
 name: Firebase Unity SDK build
 
 on:
+  schedule:
+    - cron: "0 7 * * *"  # 7am UTC = 11pm PST / 12am PDT
+  
   workflow_dispatch:
     inputs:
       unity_version:
@@ -134,47 +137,62 @@ jobs:
       unity_platform_name: Windows
       additional_cmake_flags: ${{ github.event.inputs.additional_cmake_flags }}
 
-  trigger_package:
+  trigger_reusable_package:
     name: package ${{ github.event.inputs.release_label }}
     needs: [build_android, build_ios, build_linux, build_macos, build_windows]
+    uses: ./.github/workflows/package.yml
     if: (github.event.inputs.should_trigger_package == 'true') && !cancelled() && !failure()
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout repo
-      uses: actions/checkout@v2.3.1
+    with:
+      use_new_build: '1'
+      release_label: ${{ github.event.inputs.release_label }}
+      skipIntegrationTests: ${{ github.event.inputs.skipIntegrationTests }}
+      download_android_run: ${{ github.run_id }}
+      download_ios_run: ${{ github.run_id }}
+      download_linux_run: ${{ github.run_id }}
+      download_macos_run: ${{ github.run_id }}
+      download_windows_run: ${{ github.run_id }}
+  
+  # trigger_package:
+  #   name: package ${{ github.event.inputs.release_label }}
+  #   needs: [build_android, build_ios, build_linux, build_macos, build_windows]
+  #   if: (github.event.inputs.should_trigger_package == 'true') && !cancelled() && !failure()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout repo
+  #     uses: actions/checkout@v2.3.1
 
-    - name: Setup python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.7
+  #   - name: Setup python
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: 3.7
     
-    - name: Install python deps
-      shell: bash
-      run: |
-        pip install -r scripts/gha/requirements.txt
-    - name: Generate token for GitHub API
-      # This step is necessary because the existing GITHUB_TOKEN cannot be used inside one workflow to trigger another.
-      # 
-      # Instead, generate a new token here, using our GitHub App's private key and App ID (saved as Secrets).
-      # 
-      # This method is preferred over the "personal access token" solution, as the GitHub App's scope is limited to just
-      # the firebase-cpp-sdk repository.
-      uses: tibdex/github-app-token@v1
-      id: generate-token
-      with:
-        app_id: ${{ secrets.WORKFLOW_TRIGGER_APP_ID }}
-        private_key: ${{ secrets.WORKFLOW_TRIGGER_APP_PRIVATE_KEY }}
-    - name: Use GitHub API to start workflow
-      shell: bash
-      run: |
-        set -e
-        python scripts/gha/trigger_workflow.py -t ${{ steps.generate-token.outputs.token }} -w package.yml \
-          -p use_new_build '1' \
-          -p release_label ${{ github.event.inputs.release_label }} \
-          -p skipIntegrationTests ${{ github.event.inputs.skipIntegrationTests }} \
-          -p download_android_run ${{ github.run_id }} \
-          -p download_ios_run ${{ github.run_id }} \
-          -p download_linux_run ${{ github.run_id }} \
-          -p download_macos_run ${{ github.run_id }} \
-          -p download_windows_run ${{ github.run_id }} \
-          -s 10 -A -v
+  #   - name: Install python deps
+  #     shell: bash
+  #     run: |
+  #       pip install -r scripts/gha/requirements.txt
+  #   - name: Generate token for GitHub API
+  #     # This step is necessary because the existing GITHUB_TOKEN cannot be used inside one workflow to trigger another.
+  #     # 
+  #     # Instead, generate a new token here, using our GitHub App's private key and App ID (saved as Secrets).
+  #     # 
+  #     # This method is preferred over the "personal access token" solution, as the GitHub App's scope is limited to just
+  #     # the firebase-cpp-sdk repository.
+  #     uses: tibdex/github-app-token@v1
+  #     id: generate-token
+  #     with:
+  #       app_id: ${{ secrets.WORKFLOW_TRIGGER_APP_ID }}
+  #       private_key: ${{ secrets.WORKFLOW_TRIGGER_APP_PRIVATE_KEY }}
+  #   - name: Use GitHub API to start workflow
+  #     shell: bash
+  #     run: |
+  #       set -e
+  #       python scripts/gha/trigger_workflow.py -t ${{ steps.generate-token.outputs.token }} -w package.yml \
+  #         -p use_new_build '1' \
+  #         -p release_label ${{ github.event.inputs.release_label }} \
+  #         -p skipIntegrationTests ${{ github.event.inputs.skipIntegrationTests }} \
+  #         -p download_android_run ${{ github.run_id }} \
+  #         -p download_ios_run ${{ github.run_id }} \
+  #         -p download_linux_run ${{ github.run_id }} \
+  #         -p download_macos_run ${{ github.run_id }} \
+  #         -p download_windows_run ${{ github.run_id }} \
+  #         -s 10 -A -v
