Fully setup input for nightly build, and fail building job if no zip generated (#359)

diff --git a/.github/workflows/build_android.yml b/.github/workflows/build_android.yml
--- a/.github/workflows/build_android.yml
+++ b/.github/workflows/build_android.yml
@@ -120,6 +120,16 @@ jobs:
           # TODO add handling cmake_extras
           python scripts/build_scripts/build_zips.py --platform=android --unity_root=$UNITY_ROOT_DIR --apis=${{ inputs.apis }}
 
+      - name: Check zip file
+        shell: bash
+        run: |
+          if [ -f android_unity/*.zip ]; then
+            echo "android_unity zip created."
+          else
+            echo "Fail to create android_unity zip."
+            exit 1
+          fi
+
       - name: Upload Build
         uses: actions/upload-artifact@v2
         with:
diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -112,6 +112,16 @@ jobs:
         run: |
           # TODO add handling cmake_extras
           python scripts/build_scripts/build_zips.py --platform=linux --use_boringssl=true --unity_root=$UNITY_ROOT_DIR --apis=${{ inputs.apis }}
+      
+      - name: Check zip file
+        shell: bash
+        run: |
+          if [ -f linux_unity/*.zip ]; then
+            echo "linux_unity zip created."
+          else
+            echo "Fail to create linux_unity zip."
+            exit 1
+          fi
 
       - name: Upload Build
         uses: actions/upload-artifact@v2
diff --git a/.github/workflows/build_macos.yml b/.github/workflows/build_macos.yml
--- a/.github/workflows/build_macos.yml
+++ b/.github/workflows/build_macos.yml
@@ -119,6 +119,16 @@ jobs:
           # TODO add handling cmake_extras
           python scripts/build_scripts/build_zips.py --platform=macos --unity_root=$UNITY_ROOT_DIR --use_boringssl --architecture=x86_64 --architecture=arm64 --apis=${{ inputs.apis }}
 
+      - name: Check zip file
+        shell: bash
+        run: |
+          if [ -f macos_unity/*.zip ]; then
+            echo "macos_unity zip created."
+          else
+            echo "Fail to create macos_unity zip."
+            exit 1
+          fi
+
       - name: Upload Build
         uses: actions/upload-artifact@v2
         with:
diff --git a/.github/workflows/build_windows.yml b/.github/workflows/build_windows.yml
--- a/.github/workflows/build_windows.yml
+++ b/.github/workflows/build_windows.yml
@@ -119,6 +119,16 @@ jobs:
           # TODO add handling cmake_extras
           python scripts/build_scripts/build_zips.py --platform=windows --unity_root="$UNITY_ROOT_DIR" --swig_dir="$SWIG_DIR" --apis=${{ inputs.apis }}
 
+      - name: Check zip file
+        shell: bash
+        run: |
+          if [ -f windows_unity/*.zip ]; then
+            echo "windows_unity zip created."
+          else
+            echo "Fail to create windows_unity zip."
+            exit 1
+          fi
+
       - name: Upload Build
         uses: actions/upload-artifact@v2
         with:
