test dynamic matrix

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -147,19 +147,8 @@ jobs:
         # To feed input into the job matrix, we first need to convert to a JSON
         # list. Then we can use fromJson to define the field in the matrix for the tests job.
         echo "::set-output name=apis::$( python scripts/gha/print_matrix_configuration.py -c -w integration_tests -k apis -o "${{github.event.inputs.apis}}" ${TEST_MATRIX_PARAM} )"
-        # platform=$( python scripts/gha/print_matrix_configuration.py -c -w integration_tests ${TEST_MATRIX_PARAM} -k platform -o "${{github.event.inputs.platforms}}" )
-        # echo "::set-output name=platform::${platform}"
-        # echo "::set-output name=matrix_desktop_os::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k "${platform}" -desktop_os=1)"
-        # echo "::set-output name=matrix_mobile_platform::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k "${platform}" -mobile_platform=1)"
-        # echo "::set-output name=matrix_build_platform::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k "${platform}")"
-        # echo "::set-output name=matrix_build_os::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k build_os -o "${{github.event.inputs.build_os}}")"
-        # echo "::set-output name=matrix_unity_versions::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k unity_version -o "${{github.event.inputs.unity_versions}}")"
-        # mobile_test_on=$( python scripts/gha/print_matrix_configuration.py -c -w integration_tests -k mobile_test_on -o "${{github.event.inputs.mobile_test_on}}")
-        # echo "::set-output name=mobile_test_on::${mobile_test_on}"
-        # echo "::set-output name=mobile_device::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k mobile_device -t ${mobile_test_on} -p ${platform})"
-        build_matrix=$( python scripts/gha/print_matrix_configuration.py -build_matrix -unity_versions "${{github.event.inputs.unity_versions}}" -platforms "${{github.event.inputs.platforms}}" -build_os "${{github.event.inputs.build_os}}" -ios_sdk "${{github.event.inputs.mobile_test_on}}")
-        echo ${build_matrix}
-        echo "::set-output name=build_matrix::${build_matrix}"
+        echo "::set-output name=build_matrix::$( python scripts/gha/print_matrix_configuration.py -build_matrix -unity_versions "${{github.event.inputs.unity_versions}}" -platforms "${{github.event.inputs.platforms}}" -os "${{github.event.inputs.build_os}}" -ios_sdk "${{github.event.inputs.mobile_test_on}}")"
+        echo "::set-output name=playmode_matrix::$( python scripts/gha/print_matrix_configuration.py -playmode_matrix -unity_versions "${{github.event.inputs.unity_versions}}" -platforms "${{github.event.inputs.platforms}}" -os "${{github.event.inputs.build_os}}")"
     - name: Update PR label and comment
       if: steps.set_outputs.outputs.pr_number
       run: |
@@ -172,8 +161,8 @@ jobs:
           --run_id ${{github.run_id}}
 
   build:
-    name: build-${{ matrix.unity_version }}-${{matrix.build_os}}-${{ matrix.platform }}-${{ matrix.ios_sdk }}
-    runs-on: ${{matrix.build_os}}
+    name: build-${{ matrix.unity_version }}-${{matrix.os}}-${{ matrix.platform }}-${{ matrix.ios_sdk }}
+    runs-on: ${{matrix.os}}
     if: ${{ needs.check_and_prepare.outputs.matrix_build_platform != '[]' }}
     needs: check_and_prepare
     strategy:
@@ -189,7 +178,7 @@ jobs:
     steps:
       - id: matrix_info
         run: |
-          echo "::set-output name=info::${{ matrix.unity_version }}-${{matrix.build_os}}-${{ matrix.platform }}-${{ matrix.ios_sdk }}"
+          echo "::set-output name=info::${{ matrix.unity_version }}-${{matrix.os}}-${{ matrix.platform }}-${{ matrix.ios_sdk }}"
       - uses: actions/checkout@v2
       - uses: ruby/setup-ruby@v1
         with:
@@ -280,72 +269,72 @@ jobs:
         if: ${{ !cancelled() }}
         shell: bash
         run: |
-          if [ ! -f build-results-${{steps.matrix_info.outputs.info}}.log.json ]; then
+          if [ ! -f build-results-${{ steps.matrix_info.outputs.info }}.log.json ]; then
             # No summary was created, make a placeholder one.
-            echo "__SUMMARY_MISSING__" > build-results-${{steps.matrix_info.outputs.info}}.log.json
+            echo "__SUMMARY_MISSING__" > build-results-${{ steps.matrix_info.outputs.info }}.log.json
           fi
       - name: Upload build results artifact
         uses: actions/upload-artifact@v3
         if: ${{ !cancelled() }}
         with:
           name: log-artifact
-          path: build-results-${{steps.matrix_info.outputs.info}}*
+          path: build-results-${{ steps.matrix_info.outputs.info }}*
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Upload Android integration tests artifact
         uses: actions/upload-artifact@v3
         if: contains(matrix.platform, 'Android') && ${{ !cancelled() }}
         with:
-          name: testapps-${{steps.matrix_info.outputs.info}}-Android
-          path: testapps-${{steps.matrix_info.outputs.info}}/Android
+          name: testapps-${{ steps.matrix_info.outputs.info }}-Android
+          path: testapps-${{ steps.matrix_info.outputs.info }}/Android
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Delete Android integration tests artifact
         if: contains(needs.check_and_prepare.outputs.platform, 'Android') && ${{ !cancelled() }}
         shell: bash
-        run: rm -rf testapps-${{steps.matrix_info.outputs.info}}/Android || true
+        run: rm -rf testapps-${{ steps.matrix_info.outputs.info }}/Android || true
       - name: Upload iOS integration tests artifact
         uses: actions/upload-artifact@v3
         if: contains(matrix.platform, 'iOS') && ${{ !cancelled() }}
         with:
-          name: testapps-${{steps.matrix_info.outputs.info}}-iOS
-          path: testapps-${{steps.matrix_info.outputs.info}}/iOS
+          name: testapps-${{ steps.matrix_info.outputs.info }}-iOS
+          path: testapps-${{ steps.matrix_info.outputs.info }}/iOS
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Delete iOS integration tests artifact
         if: contains(needs.check_and_prepare.outputs.platform, 'iOS') && ${{ !cancelled() }}
         shell: bash
-        run: rm -rf testapps-${{steps.matrix_info.outputs.info}}/iOS || true
+        run: rm -rf testapps-${{ steps.matrix_info.outputs.info }}/iOS || true
       - name: Upload Linux integration tests artifact
         uses: actions/upload-artifact@v3
         if: contains(matrix.platform, 'Linux') && ${{ !cancelled() }}
         with:
-          name: testapps-${{steps.matrix_info.outputs.info}}-ubuntu-latest
-          path: testapps-${{steps.matrix_info.outputs.info}}/Linux
+          name: testapps-${{ steps.matrix_info.outputs.info }}-ubuntu-latest
+          path: testapps-${{ steps.matrix_info.outputs.info }}/Linux
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Delete Linux integration tests artifact
         if: contains(needs.check_and_prepare.outputs.platform, 'Linux') && ${{ !cancelled() }}
         shell: bash
-        run: rm -rf testapps-${{steps.matrix_info.outputs.info}}/Linux || true
+        run: rm -rf testapps-${{ steps.matrix_info.outputs.info }}/Linux || true
       - name: Upload macOS integration tests artifact
         uses: actions/upload-artifact@v3
         if: contains(matrix.platform, 'macOS') && ${{ !cancelled() }}
         with:
-          name: testapps-${{steps.matrix_info.outputs.info}}-macos-latest
-          path: testapps-${{steps.matrix_info.outputs.info}}/macOS
+          name: testapps-${{ steps.matrix_info.outputs.info }}-macos-latest
+          path: testapps-${{ steps.matrix_info.outputs.info }}/macOS
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Delete macOS integration tests artifact
         if: contains(needs.check_and_prepare.outputs.platform, 'macOS') && ${{ !cancelled() }}
         shell: bash
-        run: rm -rf testapps-${{steps.matrix_info.outputs.info}}/macOS || true
+        run: rm -rf testapps-${{ steps.matrix_info.outputs.info }}/macOS || true
       - name: Upload Windows integration tests artifact
         uses: actions/upload-artifact@v3
         if: contains(matrix.platform, 'Windows') && ${{ !cancelled() }}
         with:
-          name: testapps-${{steps.matrix_info.outputs.info}}
-          path: testapps-${{steps.matrix_info.outputs.info}}/Windows
+          name: testapps-${{ steps.matrix_info.outputs.info }}
+          path: testapps-${{ steps.matrix_info.outputs.info }}/Windows
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Delete Windows integration tests artifact
         if: contains(needs.check_and_prepare.outputs.platform, 'Windows') && ${{ !cancelled() }}
         shell: bash
-        run: rm -rf testapps-${{steps.matrix_info.outputs.info}}/Windows || true
+        run: rm -rf testapps-${{ steps.matrix_info.outputs.info }}/Windows || true
       - name: Download log artifacts
         if: ${{ needs.check_and_prepare.outputs.pr_number && failure() && !cancelled() }}
         uses: actions/download-artifact@v3
@@ -366,7 +355,7 @@ jobs:
         if: ${{ !cancelled() }}
         shell: bash
         run: |
-          cat build-results-${{steps.matrix_info.outputs.info}}.log
+          cat build-results-${{ steps.matrix_info.outputs.info }}.log
           if [[ "${{ job.status }}" != "success" ]]; then
             exit 1
           fi
@@ -378,9 +367,7 @@ jobs:
     needs: check_and_prepare
     strategy:
       fail-fast: false
-      matrix:
-        unity_version: ${{ fromJson(needs.check_and_prepare.outputs.matrix_unity_versions) }}
-        os: ${{ fromJson(needs.check_and_prepare.outputs.matrix_build_os) }}
+      matrix: ${{ fromJson(needs.check_and_prepare.outputs.playmode_matrix) }}
     env:
       # LC_ALL, LANG and U3D_PASSWORD are needed for U3D.
       LC_ALL: en_US.UTF-8
@@ -389,6 +376,9 @@ jobs:
       # Disable checking for U3D updates, since it is buggy
       U3D_SKIP_UPDATE_CHECK: 1
     steps:
+      - id: matrix_info
+        run: |
+          echo "::set-output name=info::${{ matrix.unity_version }}-${{matrix.os}}-Playmode"
       - uses: actions/checkout@v2
       - uses: ruby/setup-ruby@v1
         with:
@@ -456,7 +446,7 @@ jobs:
             --ios_sdk ${{ needs.check_and_prepare.outputs.mobile_test_on }} \
             --plugin_dir ~/Downloads/firebase_unity_sdk \
             --output_directory "${{ github.workspace }}" \
-            --artifact_name "${{ matrix.unity_version }}-${{matrix.os}}-Playmode" \
+            --artifact_name "${{ steps.matrix_info.outputs.info }}" \
             --force_latest_runtime \
             --ci
       - name: Return Unity license
@@ -477,16 +467,16 @@ jobs:
         if: ${{ !cancelled() }}
         shell: bash
         run: |
-          if [ ! -f test-results-${{ matrix.unity_version }}-${{matrix.os}}-Playmode.log.json ]; then
+          if [ ! -f test-results-${{ steps.matrix_info.outputs.info }}.log.json ]; then
             # No summary was created, make a placeholder one.
-            echo "__SUMMARY_MISSING__" > test-results-${{ matrix.unity_version }}-${{matrix.os}}-Playmode.log.json
+            echo "__SUMMARY_MISSING__" > test-results-${{ steps.matrix_info.outputs.info }}.log.json
           fi
       - name: Upload test results artifact
         uses: actions/upload-artifact@v3
         if: ${{ !cancelled() }}
         with:
           name: log-artifact
-          path: test-results-${{ matrix.unity_version }}-${{matrix.os}}-Playmode*
+          path: test-results-${{ steps.matrix_info.outputs.info }}-Playmode*
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Update PR label and comment
         if: ${{ needs.check_and_prepare.outputs.pr_number && failure() && !cancelled() }}
@@ -502,7 +492,7 @@ jobs:
         if: ${{ !cancelled() }}
         shell: bash
         run: |
-          cat test-results-${{ matrix.unity_version }}-${{matrix.os}}-Playmode.log
+          cat test-results-${{ steps.matrix_info.outputs.info }}.log
           if [[ "${{ job.status }}" != "success" ]]; then
             exit 1
           fi
